FROM python:3.12-slim

WORKDIR /worker

RUN apt-get update -y && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uv

COPY worker/pyproject.toml ./pyproject.toml
COPY worker/uv.lock ./uv.lock
COPY worker/README.md ./README.md
COPY worker/src ./src

RUN uv sync --frozen --no-dev

CMD ["uv", "run", "starter-worker"]
